apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: scoring-vs
spec:
  hosts:
  - "*"
  gateways:
  - scoring-test-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: frontend-service                 
        port:
          number: 80  