# Default values for trainingjob.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: jakkaj/sampletrainer
  tag: dev
  pullPolicy: IfNotPresent

outputs:
  modelfolder: /mnt/azure/
  mountpath: /mnt/azure

build:
  number: 13