apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "trainingjob.fullname" . }}
  labels:
    app: {{ template "trainingjob.name" . }}
    chart: {{ template "trainingjob.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    buildNumber: {{ template .Values.buildNumber}}
spec:
  template:
    metadata:
      name: trainerjob
    spec:
      containers:
      - name: trainer
        image: jakkaj/sampletrainer:{{.Values.buildNumber}}
        volumeMounts:
        - mountPath: "{{.Values.modelFolder}}"
          name: volume 
        env:
        - name: MODELFOLDER
          value: "{{.Values.modelFolder}}"        
      restartPolicy: Never
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azurefile
  backoffLimit: 1