apiVersion: batch/v1
kind: Job
metadata:
  name: trainingjob-{{ .Values.build.number }}
  version: {{ .Values.build.number}}
  #name: {{ template "trainingjob.fullname" . }}
  # labels:
  #   app: {{ template "trainingjob.name" . }}
  #   chart: {{ template "trainingjob.chart" . }}
  #   release: {{ .Release.Name }}
  #   heritage: {{ .Release.Service }}
  #   buildNumber: {{ .Values.build.number}}
spec:
  template:
    metadata:
      name: trainerjob
    spec:
      containers:
      - name: trainer
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: {{ .Values.outputs.mountpath | quote}}
          name: volume 
        env:
        - name: MODELFOLDER
          value:  {{ .Values.outputs.modelfolder | quote}}        
      restartPolicy: Never
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azurefile
  backoffLimit: 1
  restartPolicy: never