apiVersion: batch/v1
kind: Job
metadata:
  name: trainerjob  
spec:
  template:
    metadata:
      name: trainerjob
    spec:
      containers:
      - name: trainer
        image: jakkaj/sampletrainer:dev
        volumeMounts:
        - mountPath: "/mnt/azure"
          name: volume 
        env:
        - name: MODELFOLDER
          value: "/mnt/azure"        
      restartPolicy: Never
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azurefilecustom
  backoffLimit: 1